// Real Glastonbury 2025 lineup data - Complete Official Lineup with ALL stages
export const realGlastonbury2025 = {
  name: "Glastonbury Festival 2025",
  dates: "June 25-29, 2025",
  lastUpdated: new Date().toISOString(),
  source: "https://www.glastonburyfestivals.co.uk/line-up/line-up-2025/",
  stages: [
    {
      id: "pyramid",
      name: "Pyramid Stage",
      acts: [
        // FRIDAY
        { id: "pyr-1", name: "The 1975", time: "22:15-23:45", day: "Friday", genre: "Indie Pop" },
        { id: "pyr-2", name: "Biffy Clyro", time: "20:15-21:15", day: "Friday", genre: "Alternative Rock" },
        { id: "pyr-3", name: "Alanis Morissette", time: "18:15-19:15", day: "Friday", genre: "Alternative Rock" },
        { id: "pyr-4", name: "TBA", time: "16:55-17:30", day: "Friday", genre: "TBA" },
        { id: "pyr-5", name: "Burning Spear", time: "15:00-16:00", day: "Friday", genre: "Reggae" },
        { id: "pyr-6", name: "CMAT", time: "13:30-14:30", day: "Friday", genre: "Country Pop" },
        { id: "pyr-7", name: "Supergrass", time: "12:00-13:00", day: "Friday", genre: "Britpop" },
        // SATURDAY
        { id: "pyr-8", name: "Neil Young and the Chrome Hearts", time: "22:00-23:45", day: "Saturday", genre: "Rock" },
        { id: "pyr-9", name: "Raye", time: "20:00-21:00", day: "Saturday", genre: "R&B" },
        { id: "pyr-10", name: "Patchwork", time: "18:15-19:15", day: "Saturday", genre: "Folk" },
        { id: "pyr-11", name: "John Fogerty", time: "16:30-17:30", day: "Saturday", genre: "Rock" },
        { id: "pyr-12", name: "The Script", time: "15:00-16:00", day: "Saturday", genre: "Pop Rock" },
        { id: "pyr-13", name: "Brandi Carlile", time: "13:30-14:30", day: "Saturday", genre: "Americana" },
        { id: "pyr-14", name: "Kaiser Chiefs", time: "12:00-13:00", day: "Saturday", genre: "Indie Rock" },
        // SUNDAY
        { id: "pyr-15", name: "Olivia Rodrigo", time: "21:45-23:15", day: "Sunday", genre: "Pop" },
        { id: "pyr-16", name: "Noah Kahan", time: "19:45-20:45", day: "Sunday", genre: "Folk Pop" },
        { id: "pyr-17", name: "Nile Rodgers & Chic", time: "18:00-19:00", day: "Sunday", genre: "Disco" },
        { id: "pyr-18", name: "Rod Stewart", time: "15:45-17:15", day: "Sunday", genre: "Rock" },
        { id: "pyr-19", name: "The Libertines", time: "14:00-15:00", day: "Sunday", genre: "Indie Rock" },
        { id: "pyr-20", name: "Celeste", time: "12:30-13:30", day: "Sunday", genre: "Soul" },
        { id: "pyr-21", name: "The Selecter", time: "11:15-12:00", day: "Sunday", genre: "Ska" },
      ],
    },
    {
      id: "other",
      name: "Other Stage",
      acts: [
        { id: "oth-1", name: "The Prodigy", time: "21:45-23:15", day: "Sunday", genre: "Electronic" },
        { id: "oth-2", name: "Wolf Alice", time: "19:45-20:45", day: "Sunday", genre: "Alternative Rock" },
        { id: "oth-3", name: "Snow Patrol", time: "18:00-19:00", day: "Sunday", genre: "Alternative Rock" },
        { id: "oth-4", name: "Turnstile", time: "16:30-17:30", day: "Sunday", genre: "Hardcore Punk" },
        { id: "oth-5", name: "Joy Crookes", time: "15:00-15:45", day: "Sunday", genre: "R&B" },
        { id: "oth-6", name: "Shaboozey", time: "13:45-14:30", day: "Sunday", genre: "Country" },
        { id: "oth-7", name: "Nadine Shah", time: "12:30-13:15", day: "Sunday", genre: "Alternative Rock" },
        { id: "oth-8", name: "Louis Dunford", time: "11:15-12:00", day: "Sunday", genre: "Indie Folk" },
        { id: "oth-9", name: "Charli XCX", time: "22:30-23:45", day: "Saturday", genre: "Pop" },
        { id: "oth-10", name: "Deftones", time: "20:30-21:30", day: "Saturday", genre: "Alternative Metal" },
        { id: "oth-11", name: "Ezra Collective", time: "18:45-19:45", day: "Saturday", genre: "Jazz" },
        { id: "oth-12", name: "Amyl & The Sniffers", time: "17:00-18:00", day: "Saturday", genre: "Punk Rock" },
        { id: "oth-13", name: "Weezer", time: "15:30-16:30", day: "Saturday", genre: "Alternative Rock" },
        { id: "oth-14", name: "Beabadoobee", time: "14:00-15:00", day: "Saturday", genre: "Indie Rock" },
        { id: "oth-15", name: "Good Neighbours", time: "12:45-13:30", day: "Saturday", genre: "Indie Pop" },
        { id: "oth-16", name: "Alessi Rose", time: "11:30-12:15", day: "Saturday", genre: "Pop" },
        { id: "oth-17", name: "Loyle Carner", time: "22:30-23:45", day: "Friday", genre: "Hip Hop" },
        { id: "oth-18", name: "Busta Rhymes", time: "20:30-21:30", day: "Friday", genre: "Hip Hop" },
        { id: "oth-19", name: "Gracie Abrams", time: "18:45-19:45", day: "Friday", genre: "Indie Pop" },
        { id: "oth-20", name: "Franz Ferdinand", time: "17:15-18:15", day: "Friday", genre: "Indie Rock" },
        { id: "oth-21", name: "Wet Leg", time: "15:45-16:45", day: "Friday", genre: "Indie Rock" },
        { id: "oth-22", name: "Inhaler", time: "14:15-15:15", day: "Friday", genre: "Indie Rock" },
        { id: "oth-23", name: "Rizzle Kicks", time: "13:00-13:45", day: "Friday", genre: "Hip Hop" },
        {
          id: "oth-24",
          name: "Fabio & Grooverider and the Outlook Orchestra",
          time: "11:30-12:30",
          day: "Friday",
          genre: "Drum & Bass",
        },
      ],
    },
    {
      id: "west-holts",
      name: "West Holts Stage",
      acts: [
        { id: "wh-1", name: "Overmono", time: "21:45-23:15", day: "Sunday", genre: "Electronic" },
        { id: "wh-2", name: "Parcels", time: "20:00-21:00", day: "Sunday", genre: "Electronic" },
        {
          id: "wh-3",
          name: "The Brian Jonestown Massacre",
          time: "18:30-19:30",
          day: "Sunday",
          genre: "Psychedelic Rock",
        },
        { id: "wh-4", name: "Goat", time: "17:00-18:00", day: "Sunday", genre: "Experimental" },
        { id: "wh-5", name: "Black Uhuru", time: "15:30-16:30", day: "Sunday", genre: "Reggae" },
        { id: "wh-6", name: "Cymande", time: "14:00-15:00", day: "Sunday", genre: "Funk" },
        {
          id: "wh-7",
          name: "Abel Selaocoe & The Bantu Ensemble",
          time: "12:30-13:30",
          day: "Sunday",
          genre: "Classical",
        },
        { id: "wh-8", name: "Thandii", time: "11:00-12:00", day: "Sunday", genre: "Soul" },
        { id: "wh-9", name: "Doechii", time: "22:15-23:45", day: "Saturday", genre: "Hip Hop" },
        { id: "wh-10", name: "Greentea Peng", time: "19:00-20:00", day: "Saturday", genre: "Neo Soul" },
        { id: "wh-11", name: "Yussef Dayes", time: "17:30-18:30", day: "Saturday", genre: "Jazz" },
        { id: "wh-12", name: "Kneecap", time: "16:00-17:00", day: "Saturday", genre: "Hip Hop" },
        { id: "wh-13", name: "Bob Vylan", time: "14:30-15:30", day: "Saturday", genre: "Punk" },
        { id: "wh-14", name: "Nilüfer Yanya", time: "13:00-14:00", day: "Saturday", genre: "Indie Rock" },
        { id: "wh-15", name: "Infinity Song", time: "11:30-12:30", day: "Saturday", genre: "R&B" },
        { id: "wh-16", name: "Maribou State", time: "22:15-23:45", day: "Friday", genre: "Electronic" },
        { id: "wh-17", name: "Denzel Curry", time: "19:00-20:00", day: "Friday", genre: "Hip Hop" },
        { id: "wh-18", name: "En Vogue", time: "17:30-18:30", day: "Friday", genre: "R&B" },
        { id: "wh-19", name: "Vieux Farka Toure", time: "16:00-17:00", day: "Friday", genre: "World Music" },
        { id: "wh-20", name: "Glass Beams", time: "14:30-15:25", day: "Friday", genre: "Psychedelic" },
        { id: "wh-21", name: "Ca7riel & Paco Amoroso", time: "13:00-14:00", day: "Friday", genre: "Latin" },
      ],
    },
    {
      id: "park",
      name: "The Park Stage",
      acts: [
        { id: "park-1", name: "The Maccabees", time: "21:15-22:30", day: "Sunday", genre: "Indie Rock" },
        { id: "park-2", name: "Future Islands", time: "19:35-20:35", day: "Sunday", genre: "Synth Pop" },
        { id: "park-3", name: "Kae Tempest", time: "18:00-19:00", day: "Sunday", genre: "Spoken Word" },
        { id: "park-4", name: "Girl in Red", time: "16:30-17:30", day: "Sunday", genre: "Indie Pop" },
        { id: "park-5", name: "Royel Otis", time: "15:15-16:00", day: "Sunday", genre: "Indie Rock" },
        { id: "park-6", name: "Katy J Pearson", time: "14:00-14:45", day: "Sunday", genre: "Indie Pop" },
        { id: "park-7", name: "Geordie Greep", time: "12:45-13:30", day: "Sunday", genre: "Experimental" },
        { id: "park-8", name: "Melin Melyn", time: "11:30-12:15", day: "Sunday", genre: "Indie Rock" },
        { id: "park-9", name: "TBA", time: "19:30-20:30", day: "Saturday", genre: "TBA" },
        { id: "park-10", name: "Gary Numan", time: "18:00-19:00", day: "Saturday", genre: "Electronic" },
        { id: "park-11", name: "Beth Gibbons", time: "21:15-22:15", day: "Saturday", genre: "Trip Hop" },
        { id: "park-12", name: "Pa Salieu", time: "16:45-17:30", day: "Saturday", genre: "Hip Hop" },
        { id: "park-13", name: "Lucy Dacus", time: "15:30-16:15", day: "Saturday", genre: "Indie Rock" },
        { id: "park-14", name: "Japanese Breakfast", time: "14:00-15:00", day: "Saturday", genre: "Indie Rock" },
        { id: "park-15", name: "Ichiko Aoba", time: "12:45-13:30", day: "Saturday", genre: "Folk" },
        { id: "park-16", name: "Yann Tiersen", time: "11:10-12:10", day: "Saturday", genre: "Instrumental" },
        { id: "park-17", name: "Anohni and the Johnsons", time: "23:00-00:15", day: "Saturday", genre: "Art Pop" },
        { id: "park-18", name: "Self Esteem", time: "21:15-22:15", day: "Friday", genre: "Pop" },
        { id: "park-19", name: "Wunderhorse", time: "19:30-20:30", day: "Friday", genre: "Rock" },
        { id: "park-20", name: "Osees", time: "18:00-19:00", day: "Friday", genre: "Garage Rock" },
        { id: "park-21", name: "English Teacher", time: "16:30-17:30", day: "Friday", genre: "Post Punk" },
        { id: "park-22", name: "Faye Webster", time: "15:15-16:00", day: "Friday", genre: "Indie Folk" },
        { id: "park-23", name: "Jalen Ngonda", time: "14:00-14:45", day: "Friday", genre: "Soul" },
        { id: "park-24", name: "John Glacier", time: "12:45-13:30", day: "Friday", genre: "Experimental" },
        { id: "park-25", name: "Horsegirl", time: "11:30-12:10", day: "Friday", genre: "Indie Rock" },
      ],
    },
    {
      id: "woodsies",
      name: "Woodsies",
      acts: [
        { id: "wood-1", name: "Jorja Smith", time: "21:30-22:45", day: "Sunday", genre: "R&B" },
        { id: "wood-2", name: "St. Vincent", time: "18:30-19:30", day: "Sunday", genre: "Art Rock" },
        { id: "wood-3", name: "Black Country, New Road", time: "17:00-18:00", day: "Sunday", genre: "Post Rock" },
        { id: "wood-4", name: "DJO", time: "15:30-16:30", day: "Sunday", genre: "Indie Pop" },
        { id: "wood-5", name: "Sprints", time: "14:00-15:00", day: "Sunday", genre: "Punk" },
        { id: "wood-6", name: "Gurriers", time: "12:30-13:30", day: "Sunday", genre: "Punk" },
        { id: "wood-7", name: "Westside Cowboy", time: "11:15-12:00", day: "Sunday", genre: "Country" },
        { id: "wood-8", name: "Scissor Sisters", time: "22:30-23:45", day: "Saturday", genre: "Dance Pop" },
        { id: "wood-9", name: "Tom Odell", time: "21:00-22:00", day: "Saturday", genre: "Pop" },
        { id: "wood-10", name: "Father John Misty", time: "19:30-20:30", day: "Saturday", genre: "Indie Folk" },
        { id: "wood-11", name: "TV on the Radio", time: "18:00-19:00", day: "Saturday", genre: "Indie Rock" },
        { id: "wood-12", name: "Nova Twins", time: "16:30-17:30", day: "Saturday", genre: "Rock" },
        { id: "wood-13", name: "Jade", time: "15:15-16:00", day: "Saturday", genre: "R&B" },
        { id: "wood-14", name: "FCUKERS", time: "14:00-14:45", day: "Saturday", genre: "Electronic" },
        { id: "wood-15", name: "Sorry", time: "12:45-13:30", day: "Saturday", genre: "Post Punk" },
        { id: "wood-16", name: "The Amazons", time: "11:30-12:15", day: "Saturday", genre: "Rock" },
        { id: "wood-17", name: "Four Tet", time: "22:30-23:45", day: "Friday", genre: "Electronic" },
        { id: "wood-18", name: "Floating Points", time: "21:00-22:00", day: "Friday", genre: "Electronic" },
        { id: "wood-19", name: "PinkPantheress", time: "19:30-20:30", day: "Friday", genre: "Pop" },
        { id: "wood-20", name: "Blossoms", time: "18:00-19:00", day: "Friday", genre: "Indie Rock" },
        { id: "wood-21", name: "Lola Young", time: "16:30-17:30", day: "Friday", genre: "Pop" },
        { id: "wood-22", name: "Shed Seven", time: "15:15-16:00", day: "Friday", genre: "Britpop" },
        { id: "wood-23", name: "Fat Dog", time: "14:00-14:45", day: "Friday", genre: "Punk" },
        { id: "wood-24", name: "Myles Smith", time: "12:45-13:30", day: "Friday", genre: "Pop" },
        { id: "wood-25", name: "TBA", time: "11:30-12:15", day: "Friday", genre: "TBA" },
      ],
    },
    {
      id: "acoustic",
      name: "Acoustic Stage",
      acts: [
        { id: "ac-1", name: "Roy Harper", time: "21:30-22:30", day: "Sunday", genre: "Folk" },
        { id: "ac-2", name: "The Bootleg Beatles", time: "20:00-21:00", day: "Sunday", genre: "Tribute" },
        { id: "ac-3", name: "Rhiannon Giddens with Dirk Powell", time: "18:30-19:30", day: "Sunday", genre: "Folk" },
        { id: "ac-4", name: "London Community Gospel Choir", time: "17:00-18:00", day: "Sunday", genre: "Gospel" },
        { id: "ac-5", name: "PP Arnold", time: "16:00-16:40", day: "Sunday", genre: "Soul" },
        { id: "ac-6", name: "The Riptide Movement", time: "15:00-15:40", day: "Sunday", genre: "Rock" },
        { id: "ac-7", name: "Michele Stodart", time: "14:00-14:40", day: "Sunday", genre: "Folk" },
        { id: "ac-8", name: "The Henry Girls", time: "13:00-13:40", day: "Sunday", genre: "Folk" },
        { id: "ac-9", name: "Toby Lee", time: "12:10-12:40", day: "Sunday", genre: "Folk" },
        {
          id: "ac-10",
          name: "Dawn Landes & Friends perform The Glow",
          time: "11:30-12:00",
          day: "Sunday",
          genre: "Folk",
        },
        { id: "ac-11", name: "Nick Lowe", time: "21:30-22:45", day: "Saturday", genre: "Rock" },
        { id: "ac-12", name: "Hothouse Flowers", time: "20:00-21:00", day: "Saturday", genre: "Rock" },
        { id: "ac-13", name: "Jeremy Loops", time: "18:30-19:30", day: "Saturday", genre: "Folk" },
        { id: "ac-14", name: "The Coronas", time: "17:10-18:00", day: "Saturday", genre: "Rock" },
        { id: "ac-15", name: "The Bluebells", time: "16:10-16:50", day: "Saturday", genre: "Pop" },
        {
          id: "ac-16",
          name: "Not Completely Unknown A Celebration of Kirsty MacColl",
          time: "15:00-16:00",
          day: "Saturday",
          genre: "Tribute",
        },
        { id: "ac-17", name: "Sophie B. Hawkins", time: "14:00-14:40", day: "Saturday", genre: "Pop" },
        { id: "ac-18", name: "Oisin Leech", time: "13:00-13:40", day: "Saturday", genre: "Folk" },
        { id: "ac-19", name: "Lorraine Nash", time: "12:10-12:40", day: "Saturday", genre: "Folk" },
        { id: "ac-20", name: "Henry Grace", time: "11:30-12:00", day: "Saturday", genre: "Folk" },
        { id: "ac-21", name: "Ani DiFranco", time: "21:30-22:45", day: "Friday", genre: "Folk" },
        { id: "ac-22", name: "The Searchers", time: "20:00-21:00", day: "Friday", genre: "Rock" },
        { id: "ac-23", name: "Dhani Harrison", time: "18:30-19:30", day: "Friday", genre: "Rock" },
        { id: "ac-24", name: "Billie Marten", time: "17:00-18:00", day: "Friday", genre: "Folk" },
        { id: "ac-25", name: "Skerryvore", time: "16:00-16:40", day: "Friday", genre: "Celtic" },
        { id: "ac-26", name: "Hugh Cornwell", time: "15:00-15:40", day: "Friday", genre: "Punk" },
        { id: "ac-27", name: "Gabrielle Aplin", time: "14:00-14:40", day: "Friday", genre: "Pop" },
        { id: "ac-28", name: "Tift Merritt", time: "13:00-13:40", day: "Friday", genre: "Country" },
        { id: "ac-29", name: "Nadia Reid", time: "12:10-12:40", day: "Friday", genre: "Folk" },
        { id: "ac-30", name: "Our Man in the Field", time: "11:30-12:00", day: "Friday", genre: "Folk" },
      ],
    },
    {
      id: "avalon",
      name: "Avalon Stage",
      acts: [
        { id: "av-1", name: "Sam Ryder", time: "19:50-20:50", day: "Sunday", genre: "Pop" },
        { id: "av-2", name: "The Big Moon", time: "18:20-19:20", day: "Sunday", genre: "Indie Rock" },
        { id: "av-3", name: "My Baby", time: "16:50-17:50", day: "Sunday", genre: "Blues Rock" },
        { id: "av-4", name: "The Horne Section", time: "15:20-16:20", day: "Sunday", genre: "Comedy" },
        { id: "av-5", name: "Brooke Combe", time: "13:55-14:50", day: "Sunday", genre: "Pop" },
        { id: "av-6", name: "Talisk", time: "12:30-13:25", day: "Sunday", genre: "Celtic" },
        { id: "av-7", name: "Dea Matrona", time: "11:25-12:05", day: "Sunday", genre: "Rock" },
        { id: "av-8", name: "Hard-Fi", time: "23:10-00:20", day: "Sunday", genre: "Indie Rock" },
        { id: "av-9", name: "Tom Walker", time: "21:40-22:40", day: "Saturday", genre: "Pop" },
        { id: "av-10", name: "Rachel Chinouriri", time: "20:10-21:10", day: "Saturday", genre: "R&B" },
        { id: "av-11", name: "Jade Bird", time: "18:40-19:40", day: "Saturday", genre: "Country" },
        { id: "av-12", name: "The Amy Winehouse Band", time: "17:10-18:10", day: "Saturday", genre: "Soul" },
        { id: "av-13", name: "Jamie Cullum", time: "15:40-16:40", day: "Saturday", genre: "Jazz" },
        { id: "av-14", name: "Stephen Wilson Jr.", time: "14:15-15:10", day: "Saturday", genre: "Country" },
        { id: "av-15", name: "Bess Atwell", time: "12:50-13:45", day: "Saturday", genre: "Folk" },
        { id: "av-16", name: "Fülü", time: "11:30-12:20", day: "Saturday", genre: "World Music" },
        { id: "av-17", name: "The Fratellis", time: "23:05-00:20", day: "Saturday", genre: "Indie Rock" },
        { id: "av-18", name: "The Magic Numbers", time: "20:05-21:05", day: "Friday", genre: "Indie Pop" },
        { id: "av-19", name: "Orla Gartland", time: "18:35-19:35", day: "Friday", genre: "Indie Pop" },
        { id: "av-20", name: "Ash", time: "17:05-18:05", day: "Friday", genre: "Rock" },
        { id: "av-21", name: "Paris Paloma", time: "15:35-16:35", day: "Friday", genre: "Pop" },
        { id: "av-22", name: "Rumba de Bodas", time: "14:10-15:05", day: "Friday", genre: "Latin" },
        { id: "av-23", name: "Beans on Toast", time: "12:50-13:40", day: "Friday", genre: "Folk" },
      ],
    },
    {
      id: "shangri-la",
      name: "Shangri-La Stage",
      acts: [
        { id: "sl-1", name: "Snapped Ankles", time: "03:30-04:15", day: "Monday", genre: "Post Punk" },
        { id: "sl-2", name: "Marc Rebillet", time: "02:00-03:00", day: "Monday", genre: "Electronic" },
        { id: "sl-3", name: "Fizzy Gillespie", time: "01:30-01:45", day: "Monday", genre: "Comedy" },
        { id: "sl-4", name: "Bambie Thug", time: "23:00-00:00", day: "Sunday", genre: "Pop" },
        { id: "sl-5", name: "BCUC", time: "00:30-01:30", day: "Monday", genre: "Experimental" },
        { id: "sl-6", name: "Fatboy Slim", time: "01:00-02:30", day: "Sunday", genre: "Electronic" },
        { id: "sl-7", name: "TBA", time: "00:00-00:45", day: "Sunday", genre: "TBA" },
        { id: "sl-8", name: "Jehnny Beth (Savages) DJ Set", time: "23:00-23:45", day: "Saturday", genre: "Post Punk" },
        { id: "sl-9", name: "Beth", time: "02:45-03:00", day: "Sunday", genre: "Electronic" },
        { id: "sl-10", name: "Lady Shaka B2B Jael", time: "05:00-06:00", day: "Sunday", genre: "Electronic" },
        { id: "sl-11", name: "Example", time: "02:45-03:45", day: "Saturday", genre: "Hip Hop" },
        { id: "sl-12", name: "Ca7riel & Paco Amoroso", time: "01:15-02:15", day: "Saturday", genre: "Latin" },
        { id: "sl-13", name: "Kae Tempest", time: "00:00-00:45", day: "Saturday", genre: "Spoken Word" },
        { id: "sl-14", name: "Turno", time: "22:40-23:30", day: "Friday", genre: "Electronic" },
        {
          id: "sl-15",
          name: "Simula B2B SPY B2B Skantia X ft. Jakes",
          time: "20:40-21:40",
          day: "Friday",
          genre: "Drum & Bass",
        },
        { id: "sl-16", name: "Bou B2B DJ Die B2B T>I", time: "19:40-20:40", day: "Friday", genre: "Drum & Bass" },
        { id: "sl-17", name: "Oko", time: "18:00-18:50", day: "Friday", genre: "Electronic" },
        { id: "sl-18", name: "Craig Charles & Friends", time: "14:00-18:00", day: "Friday", genre: "Funk" },
        { id: "sl-19", name: "Born on Road AV 3.0", time: "02:00-03:00", day: "Friday", genre: "Electronic" },
        { id: "sl-20", name: "A Little Sound & Guests", time: "00:45-01:45", day: "Friday", genre: "Electronic" },
        { id: "sl-21", name: "Ishmael Ensemble", time: "23:30-00:15", day: "Thursday", genre: "Jazz" },
        { id: "sl-22", name: "KOG", time: "22:15-23:00", day: "Thursday", genre: "Electronic" },
        { id: "sl-23", name: "DJ Bilska", time: "21:45-22:15", day: "Thursday", genre: "Electronic" },
        { id: "sl-24", name: "Jamu", time: "21:00-21:45", day: "Thursday", genre: "Electronic" },
        { id: "sl-25", name: "Fizzy Gillespie", time: "20:30-21:00", day: "Thursday", genre: "Comedy" },
        { id: "sl-26", name: "Cassyette vs Filthy Pig", time: "19:15-19:45", day: "Thursday", genre: "Rock" },
        { id: "sl-27", name: "Polly Acid Box", time: "18:00-18:30", day: "Thursday", genre: "Electronic" },
        { id: "sl-28", name: "Shantel & Bucovina Club", time: "17:15-18:00", day: "Thursday", genre: "World Music" },
        { id: "sl-29", name: "Frente Cumbiero", time: "16:00-16:45", day: "Thursday", genre: "Cumbia" },
        { id: "sl-30", name: "DJ Chris Tofu", time: "16:45-17:15", day: "Thursday", genre: "Electronic" },
      ],
    },
    {
      id: "glade",
      name: "Glade",
      acts: [
        { id: "gl-1", name: "Goldie (Live)", time: "23:15-00:15", day: "Monday", genre: "Drum & Bass" },
        { id: "gl-2", name: "Deep Dish", time: "20:15-21:15", day: "Sunday", genre: "House" },
        { id: "gl-3", name: "The Orb", time: "19:15-20:15", day: "Sunday", genre: "Ambient" },
        { id: "gl-4", name: "Third World", time: "18:00-19:00", day: "Sunday", genre: "Reggae" },
        { id: "gl-5", name: "Omega Nebula", time: "16:30-17:30", day: "Sunday", genre: "Electronic" },
        { id: "gl-6", name: "K.O.G", time: "15:00-16:00", day: "Sunday", genre: "Electronic" },
        { id: "gl-7", name: "Channel One Sound System", time: "13:15-14:30", day: "Sunday", genre: "Dub" },
        { id: "gl-8", name: "Don Letts DJ Set", time: "12:00-13:15", day: "Sunday", genre: "Reggae" },
        { id: "gl-9", name: "Sherelle", time: "00:30-02:00", day: "Monday", genre: "Drum & Bass" },
        {
          id: "gl-10",
          name: "A Guy Called Gerald + The Jungle Orchestra",
          time: "21:45-22:45",
          day: "Sunday",
          genre: "Jungle",
        },
        { id: "gl-11", name: "Leftfield", time: "22:30-23:45", day: "Saturday", genre: "Electronic" },
        { id: "gl-12", name: "Max Cooper (Live A/V)", time: "20:30-22:00", day: "Saturday", genre: "Techno" },
        { id: "gl-13", name: "Annie Mac", time: "18:55-20:10", day: "Saturday", genre: "Electronic" },
        { id: "gl-14", name: "Nabihah Iqbal (DJ)", time: "17:40-18:55", day: "Saturday", genre: "Electronic" },
        {
          id: "gl-15",
          name: "Dele Sosemi Afrobeat Experience",
          time: "16:30-17:30",
          day: "Saturday",
          genre: "Afrobeat",
        },
        { id: "gl-16", name: "Tunng", time: "15:00-16:00", day: "Saturday", genre: "Folk Electronic" },
        { id: "gl-17", name: "Electric Jalaba", time: "13:30-14:30", day: "Saturday", genre: "Electronic" },
        { id: "gl-18", name: "Channel One Sound System", time: "12:00-13:00", day: "Saturday", genre: "Dub" },
        { id: "gl-19", name: "Amelie Lens", time: "01:30-02:55", day: "Sunday", genre: "Techno" },
        { id: "gl-20", name: "Richie Hawtin", time: "00:00-01:30", day: "Sunday", genre: "Techno" },
        { id: "gl-21", name: "Shygirl presents: Club Shy", time: "22:10-23:10", day: "Friday", genre: "Electronic" },
        {
          id: "gl-22",
          name: "Kettama B2B Interplanetary Criminal",
          time: "20:45-22:00",
          day: "Friday",
          genre: "Techno",
        },
        { id: "gl-23", name: "Daniel Avery B2B Imogen", time: "19:30-20:45", day: "Friday", genre: "Techno" },
        { id: "gl-24", name: "Fish56octogan", time: "18:30-19:30", day: "Friday", genre: "Electronic" },
        { id: "gl-25", name: "K Klass", time: "17:45-18:25", day: "Friday", genre: "House" },
        {
          id: "gl-26",
          name: "Carl Cox & Eric Powell's Mobile Disco",
          time: "14:25-17:25",
          day: "Friday",
          genre: "Techno",
        },
        { id: "gl-27", name: "Crazy P (DJ)", time: "13:10-14:10", day: "Friday", genre: "House" },
        { id: "gl-28", name: "Bel Cobain", time: "12:00-13:00", day: "Friday", genre: "Electronic" },
        { id: "gl-29", name: "Skepta B2B Mochakk B2B Carlita", time: "23:15-00:30", day: "Saturday", genre: "Grime" },
        { id: "gl-30", name: "Seth Troxler", time: "00:30-01:45", day: "Sunday", genre: "House" },
        { id: "gl-31", name: "Damian Lazarus", time: "01:45-02:55", day: "Sunday", genre: "Techno" },
        { id: "gl-32", name: "Joy Orbison", time: "23:00-00:30", day: "Friday", genre: "UK Garage" },
        {
          id: "gl-33",
          name: "Ross from Friends presents: Bubble Love",
          time: "20:30-21:45",
          day: "Thursday",
          genre: "House",
        },
        { id: "gl-34", name: "Lauren Lo Sung", time: "19:30-20:30", day: "Thursday", genre: "Electronic" },
        { id: "gl-35", name: "Marshall Jefferson", time: "18:15-19:30", day: "Thursday", genre: "House" },
        { id: "gl-36", name: "MJ Cole presents: Sincere", time: "17:15-18:15", day: "Thursday", genre: "UK Garage" },
        { id: "gl-37", name: "Eliza Rose", time: "21:45-23:00", day: "Thursday", genre: "House" },
        { id: "gl-38", name: "Sally C", time: "00:30-02:00", day: "Friday", genre: "House" },
      ],
    },
    {
      id: "arcadia",
      name: "Arcadia",
      acts: [
        { id: "arc-1", name: "Girls Dont Sync", time: "22:30-23:30", day: "Sunday", genre: "Electronic" },
        { id: "arc-2", name: "Dr Banana B2B Gallegos", time: "21:30-22:30", day: "Sunday", genre: "Electronic" },
        { id: "arc-3", name: "Jeremiah Asiamah", time: "20:00-21:00", day: "Sunday", genre: "Electronic" },
        { id: "arc-4", name: "Shy FX B2B Eats Everything", time: "00:10-01:30", day: "Monday", genre: "Drum & Bass" },
        { id: "arc-5", name: "Basslayerz B2B Born on Road", time: "01:30-02:30", day: "Monday", genre: "Drum & Bass" },
        { id: "arc-6", name: "BRU-C", time: "23:40-00:10", day: "Monday", genre: "Drum & Bass" },
        {
          id: "arc-7",
          name: "Groove Armada B2B Jungle (DJ Set)",
          time: "02:00-03:00",
          day: "Sunday",
          genre: "Electronic",
        },
        { id: "arc-8", name: "Four Tet", time: "00:00-01:00", day: "Sunday", genre: "Electronic" },
        {
          id: "arc-9",
          name: "Annie Mac B2B Jamz Supernova",
          time: "01:00-02:00",
          day: "Sunday",
          genre: "Electronic",
        },
        { id: "arc-10", name: "Michael Bibi B2B Solomun", time: "22:50-23:50", day: "Saturday", genre: "House" },
        { id: "arc-11", name: "Hannah Wants", time: "21:55-22:50", day: "Saturday", genre: "House" },
        { id: "arc-12", name: "Danny Howard", time: "21:00-21:55", day: "Saturday", genre: "House" },
        { id: "arc-13", name: "Becky Hill", time: "20:00-21:00", day: "Saturday", genre: "Dance" },
        { id: "arc-14", name: "Max Cooper (Live A/V)", time: "22:50-23:50", day: "Friday", genre: "Techno" },
        { id: "arc-15", name: "Optimo (Espacio)", time: "21:55-22:50", day: "Friday", genre: "Electronic" },
        { id: "arc-16", name: "Logic 1000", time: "21:00-21:55", day: "Friday", genre: "House" },
        { id: "arc-17", name: "Job Jobse B2B Palms Trax", time: "02:00-03:00", day: "Saturday", genre: "House" },
        { id: "arc-18", name: "Romy", time: "01:00-02:00", day: "Saturday", genre: "Electronic" },
        { id: "arc-19", name: "Sonny Fodera", time: "00:00-01:00", day: "Saturday", genre: "House" },
      ],
    },
    {
      id: "lonely-hearts",
      name: "Lonely Hearts Club",
      acts: [
        {
          id: "lhc-1",
          name: "Faster Horses B2B Morgan Seatree",
          time: "22:00-23:30",
          day: "Sunday",
          genre: "Electronic",
        },
        { id: "lhc-2", name: "Sim0ne [Teletech Presents]", time: "23:30-01:00", day: "Monday", genre: "Techno" },
        { id: "lhc-3", name: "Emma-Jean Thackray", time: "18:30-19:30", day: "Sunday", genre: "Jazz" },
        { id: "lhc-4", name: "Snapped Ankles", time: "17:00-18:00", day: "Sunday", genre: "Post Punk" },
        { id: "lhc-5", name: "Mermaid Chunky", time: "15:30-16:30", day: "Sunday", genre: "Electronic" },
        { id: "lhc-6", name: "Gardna: Time to Move", time: "14:00-15:00", day: "Sunday", genre: "Hip Hop" },
        {
          id: "lhc-7",
          name: "Mungos Hi-Fi ft Eva Lazarus & Aziza Jaye",
          time: "12:00-14:00",
          day: "Sunday",
          genre: "Dub",
        },
        { id: "lhc-8", name: "Mozey", time: "01:45-03:00", day: "Sunday", genre: "Electronic" },
        { id: "lhc-9", name: "Hybrid Minds", time: "00:15-01:45", day: "Sunday", genre: "Drum & Bass" },
        { id: "lhc-10", name: "Koven", time: "23:00-00:15", day: "Sunday", genre: "Drum & Bass" },
        { id: "lhc-11", name: "A.G. Cook", time: "20:30-21:30", day: "Saturday", genre: "Electronic" },
        { id: "lhc-12", name: "Biig Piig", time: "19:30-20:30", day: "Saturday", genre: "R&B" },
        { id: "lhc-13", name: "Frankie Stew & Harvey Gunn", time: "18:00-19:00", day: "Saturday", genre: "Hip Hop" },
        { id: "lhc-14", name: "Maverick Sabre", time: "16:30-17:30", day: "Saturday", genre: "Hip Hop" },
        { id: "lhc-15", name: "Luvcat", time: "15:00-16:00", day: "Saturday", genre: "Electronic" },
        { id: "lhc-16", name: "Humble the Great", time: "13:30-14:30", day: "Saturday", genre: "Hip Hop" },
        { id: "lhc-17", name: "Nat Oaks", time: "12:00-13:00", day: "Saturday", genre: "Electronic" },
        { id: "lhc-18", name: "Amelie Lens", time: "01:30-03:00", day: "Saturday", genre: "Techno" },
        { id: "lhc-19", name: "Camelphat", time: "00:00-01:30", day: "Saturday", genre: "House" },
        { id: "lhc-20", name: "Fatboy Slim", time: "22:30-00:00", day: "Friday", genre: "Electronic" },
        { id: "lhc-21", name: "Vintage Culture", time: "21:00-22:30", day: "Friday", genre: "House" },
        { id: "lhc-22", name: "Rudim3ntal", time: "20:00-20:45", day: "Friday", genre: "Drum & Bass" },
        { id: "lhc-23", name: "Bashy", time: "19:00-19:45", day: "Friday", genre: "Hip Hop" },
        { id: "lhc-24", name: "Sasha Keable", time: "17:45-18:45", day: "Friday", genre: "R&B" },
        { id: "lhc-25", name: "Bawo", time: "16:15-17:15", day: "Friday", genre: "Electronic" },
        { id: "lhc-26", name: "Bricknasty", time: "15:00-16:00", day: "Friday", genre: "Hip Hop" },
        { id: "lhc-27", name: "Rubii", time: "14:00-14:30", day: "Friday", genre: "R&B" },
        { id: "lhc-28", name: "Mobo Unsung Showcase", time: "12:00-13:30", day: "Friday", genre: "Various" },
        { id: "lhc-29", name: "P-Rallel B2B Zack Fox", time: "00:00-01:30", day: "Friday", genre: "Hip Hop" },
        { id: "lhc-30", name: "Nooriyah", time: "22:30-00:00", day: "Thursday", genre: "R&B" },
        { id: "lhc-31", name: "Major League DJz", time: "21:00-22:30", day: "Thursday", genre: "Amapiano" },
        {
          id: "lhc-32",
          name: "Changing Currents B2B FS Green",
          time: "19:30-21:00",
          day: "Thursday",
          genre: "Electronic",
        },
        { id: "lhc-33", name: "Hitech", time: "18:00-19:30", day: "Thursday", genre: "Electronic" },
        { id: "lhc-34", name: "Bambii B2B Jarreau Vandal", time: "01:30-03:00", day: "Friday", genre: "Electronic" },
      ],
    },
    {
      id: "levels",
      name: "Levels",
      acts: [
        { id: "lev-1", name: "Seth Troxler", time: "23:30-01:00", day: "Monday", genre: "House" },
        { id: "lev-2", name: "Josh Baker", time: "22:00-23:30", day: "Sunday", genre: "Electronic" },
        { id: "lev-3", name: "Pawsa", time: "20:30-22:00", day: "Sunday", genre: "House" },
        { id: "lev-4", name: "Chloe Caillet", time: "19:00-20:30", day: "Sunday", genre: "House" },
        { id: "lev-5", name: "Kilimanjaro B2B Tsha", time: "16:00-17:30", day: "Sunday", genre: "Electronic" },
        { id: "lev-6", name: "Jazzy", time: "14:45-16:00", day: "Sunday", genre: "House" },
        { id: "lev-7", name: "Rio Tashan", time: "13:15-14:45", day: "Sunday", genre: "House" },
        { id: "lev-8", name: "Dani Whylie", time: "12:00-13:15", day: "Sunday", genre: "Electronic" },
        { id: "lev-9", name: "Groove Armada", time: "01:00-02:30", day: "Monday", genre: "Electronic" },
        { id: "lev-10", name: "Jyoty", time: "01:15-03:00", day: "Sunday", genre: "Electronic" },
        { id: "lev-11", name: "Modeselektor (DJ)", time: "22:30-00:00", day: "Saturday", genre: "Electronic" },
        {
          id: "lev-12",
          name: "Erol Alkan B2B Ewan McVicar",
          time: "21:00-22:30",
          day: "Saturday",
          genre: "Electronic",
        },
        { id: "lev-13", name: "Haai B2B Romy", time: "19:30-21:00", day: "Saturday", genre: "Electronic" },
        { id: "lev-14", name: "Chaos in the CBD", time: "18:00-19:30", day: "Saturday", genre: "Electronic" },
        { id: "lev-15", name: "Berlioz", time: "16:30-18:00", day: "Saturday", genre: "Electronic" },
        { id: "lev-16", name: "Jungle (DJ)", time: "15:00-16:30", day: "Saturday", genre: "Drum & Bass" },
        { id: "lev-17", name: "DJ Paulette", time: "13:30-15:00", day: "Saturday", genre: "House" },
        { id: "lev-18", name: "Ella Knight", time: "12:00-13:30", day: "Saturday", genre: "Electronic" },
        { id: "lev-19", name: "Calibre", time: "01:45-03:00", day: "Saturday", genre: "Drum & Bass" },
        {
          id: "lev-20",
          name: "Goldie B2B Special Request",
          time: "00:15-01:45",
          day: "Saturday",
          genre: "Drum & Bass",
        },
        { id: "lev-21", name: "LTJ Bukem", time: "23:00-00:15", day: "Saturday", genre: "Drum & Bass" },
        { id: "lev-22", name: "Lens w/ Dread MC", time: "21:45-23:00", day: "Friday", genre: "Drum & Bass" },
        { id: "lev-23", name: "Notion", time: "20:30-21:45", day: "Friday", genre: "Drum & Bass" },
        { id: "lev-24", name: "Conducta", time: "19:15-20:30", day: "Friday", genre: "UK Garage" },
        { id: "lev-25", name: "Oppidan B2B Sicaria", time: "17:45-19:15", day: "Friday", genre: "Electronic" },
        { id: "lev-26", name: "Arthi", time: "16:35-17:45", day: "Friday", genre: "Electronic" },
        { id: "lev-27", name: "Katy B (Live)", time: "16:15-16:35", day: "Friday", genre: "Electronic" },
        { id: "lev-28", name: "DJ EZ", time: "15:00-16:15", day: "Friday", genre: "UK Garage" },
        { id: "lev-29", name: "G33", time: "13:30-15:00", day: "Friday", genre: "Electronic" },
        { id: "lev-30", name: "Bad B!tch Dubz", time: "12:00-13:30", day: "Friday", genre: "Dubstep" },
        {
          id: "lev-31",
          name: "Confidence Man (DJ) B2B Job Jobse",
          time: "21:00-23:00",
          day: "Thursday",
          genre: "Electronic",
        },
        { id: "lev-32", name: "Palms Trax", time: "19:30-21:00", day: "Thursday", genre: "House" },
        { id: "lev-33", name: "Peach B2B Club Fitness", time: "18:00-19:30", day: "Thursday", genre: "Electronic" },
        { id: "lev-34", name: "Marie Davidson", time: "23:30-01:00", day: "Friday", genre: "Techno" },
        { id: "lev-35", name: "Adiel", time: "01:00-03:00", day: "Friday", genre: "Techno" },
      ],
    },
    {
      id: "iicon",
      name: "Iicon",
      acts: [
        { id: "iic-1", name: "DJ Storm", time: "03:30-05:00", day: "Monday", genre: "Drum & Bass" },
        { id: "iic-2", name: "Nia Archives (DJ Set)", time: "02:00-03:30", day: "Monday", genre: "Drum & Bass" },
        { id: "iic-3", name: "Sub Focus", time: "00:30-02:00", day: "Monday", genre: "Drum & Bass" },
        { id: "iic-4", name: "Sippin' T", time: "23:00-00:30", day: "Sunday", genre: "Electronic" },
        { id: "iic-5", name: "Raggs", time: "21:30-23:00", day: "Sunday", genre: "Electronic" },
        { id: "iic-6", name: "Bushbby", time: "20:00-21:30", day: "Sunday", genre: "Electronic" },
        { id: "iic-7", name: "Blawan (DJ Set)", time: "03:30-06:00", day: "Sunday", genre: "Techno" },
        { id: "iic-8", name: "Benji B", time: "01:30-03:30", day: "Sunday", genre: "Electronic" },
        { id: "iic-9", name: "Paranoid London (Live)", time: "00:30-01:30", day: "Sunday", genre: "Acid House" },
        { id: "iic-10", name: "Shyboi", time: "22:15-00:30", day: "Saturday", genre: "Electronic" },
        { id: "iic-11", name: "Makadsi", time: "20:00-22:15", day: "Saturday", genre: "Electronic" },
        { id: "iic-12", name: "Freakenstein", time: "03:30-06:00", day: "Saturday", genre: "Electronic" },
        { id: "iic-13", name: "Two Shell", time: "02:00-03:30", day: "Saturday", genre: "Electronic" },
        { id: "iic-14", name: "Cybotron", time: "01:00-02:00", day: "Saturday", genre: "Electro" },
        { id: "iic-15", name: "Modeselektor (DJ Set)", time: "22:15-01:00", day: "Friday", genre: "Electronic" },
        { id: "iic-16", name: "EMA", time: "20:00-22:15", day: "Friday", genre: "Electronic" },
        { id: "iic-17", name: "Adam Shelton", time: "01:00-03:00", day: "Friday", genre: "Techno" },
        { id: "iic-18", name: "Thog", time: "21:30-23:00", day: "Thursday", genre: "Electronic" },
        { id: "iic-19", name: "Tash LC", time: "20:00-21:30", day: "Thursday", genre: "Electronic" },
        { id: "iic-20", name: "Pearson Sound", time: "23:00-01:00", day: "Friday", genre: "Electronic" },
      ],
    },
    {
      id: "kinetic",
      name: "Kinetic",
      acts: [
        {
          id: "kin-1",
          name: "Yunji B2B Mar Vista B2B H4rdy B2B",
          time: "21:00-22:30",
          day: "Sunday",
          genre: "Electronic",
        },
        { id: "kin-2", name: "Daytimers Family", time: "22:30-00:00", day: "Monday", genre: "Electronic" },
        { id: "kin-3", name: "Phina", time: "20:00-21:00", day: "Sunday", genre: "Electronic" },
        {
          id: "kin-4",
          name: "AUM presents: The Electronic Diaspora",
          time: "01:00-05:00",
          day: "Monday",
          genre: "Electronic",
        },
        { id: "kin-5", name: "Manami", time: "00:00-01:00", day: "Monday", genre: "Electronic" },
        { id: "kin-6", name: "Shades on (Wonka & D.A.D)", time: "03:00-06:00", day: "Sunday", genre: "Electronic" },
        { id: "kin-7", name: "Resist & FRD", time: "02:00-03:00", day: "Sunday", genre: "Electronic" },
        { id: "kin-8", name: "Dismantle", time: "00:30-02:00", day: "Sunday", genre: "Electronic" },
        { id: "kin-9", name: "Arlo", time: "23:00-00:30", day: "Sunday", genre: "Electronic" },
        { id: "kin-10", name: "Paree", time: "22:00-23:00", day: "Saturday", genre: "Electronic" },
        { id: "kin-11", name: "Red Alert", time: "21:00-22:00", day: "Saturday", genre: "Electronic" },
        { id: "kin-12", name: "Faith", time: "20:00-21:00", day: "Saturday", genre: "Electronic" },
        {
          id: "kin-13",
          name: "Kaisha B2B A-Star B2B Rusty",
          time: "05:00-06:00",
          day: "Saturday",
          genre: "Electronic",
        },
        { id: "kin-14", name: "Dope Ammo B2B Jim Bitch", time: "04:00-05:00", day: "Saturday", genre: "Electronic" },
        {
          id: "kin-15",
          name: "Origin8a & Propa B2B Toby Ross",
          time: "03:00-04:00",
          day: "Saturday",
          genre: "Electronic",
        },
        {
          id: "kin-16",
          name: "Cheff the Boy B2B Anna Prank - Hardcore",
          time: "01:00-02:00",
          day: "Saturday",
          genre: "Hardcore",
        },
        { id: "kin-17", name: "Kasra", time: "00:00-01:00", day: "Saturday", genre: "Drum & Bass" },
        { id: "kin-18", name: "Uncle Dugs (DNB Rinse Out)", time: "23:00-00:00", day: "Friday", genre: "Drum & Bass" },
        {
          id: "kin-19",
          name: "Daddy Nature B2B Dansey (Old Skool)",
          time: "22:00-23:00",
          day: "Friday",
          genre: "Breakbeat",
        },
        { id: "kin-20", name: "Altern 8 (Rave Classics)", time: "21:00-22:00", day: "Friday", genre: "Rave" },
        { id: "kin-21", name: "TBA", time: "20:00-21:00", day: "Friday", genre: "TBA" },
        { id: "kin-22", name: "Jimena Angel", time: "20:00-21:30", day: "Thursday", genre: "Electronic" },
        { id: "kin-23", name: "Jam Scones", time: "19:00-20:00", day: "Thursday", genre: "Electronic" },
        { id: "kin-24", name: "Three Thirty Three", time: "18:00-19:00", day: "Thursday", genre: "Electronic" },
        { id: "kin-25", name: "Jak & Eli", time: "00:30-02:00", day: "Friday", genre: "Electronic" },
        { id: "kin-26", name: "Kianna", time: "23:30-00:30", day: "Thursday", genre: "Electronic" },
        { id: "kin-27", name: "Kyma", time: "22:30-23:30", day: "Thursday", genre: "Electronic" },
        { id: "kin-28", name: "Lazlo Legeeza", time: "21:30-22:30", day: "Thursday", genre: "Electronic" },
        { id: "kin-29", name: "Gold Dubs", time: "02:00-03:00", day: "Friday", genre: "Electronic" },
        { id: "kin-30", name: "Stuart Warren Hill (AV)", time: "00:00-01:30", day: "Thursday", genre: "Electronic" },
        { id: "kin-31", name: "Puttyrubber (AV)", time: "22:00-23:00", day: "Wednesday", genre: "Electronic" },
        {
          id: "kin-32",
          name: "Ivan Black with Holotronica VJs",
          time: "20:00-22:00",
          day: "Wednesday",
          genre: "Electronic",
        },
        { id: "kin-33", name: "DJ Cheeba (AV)", time: "01:30-03:00", day: "Thursday", genre: "Electronic" },
      ],
    },
    // Continue with more stages...
    {
      id: "left-field",
      name: "Left Field",
      acts: [
        { id: "lf-1", name: "Grandson", time: "21:00-22:00", day: "Sunday", genre: "Rock" },
        { id: "lf-2", name: "Red Rum Club", time: "18:40-19:20", day: "Sunday", genre: "Indie Rock" },
        { id: "lf-3", name: "Reverend and the Makers", time: "19:50-20:30", day: "Sunday", genre: "Indie Rock" },
        { id: "lf-4", name: "Du Blonde", time: "17:35-18:10", day: "Sunday", genre: "Rock" },
        { id: "lf-5", name: "The Halfway Kid", time: "16:30-17:05", day: "Sunday", genre: "Folk" },
        {
          id: "lf-6",
          name: "Radical Round Up: with Billy Bragg",
          time: "15:00-16:00",
          day: "Sunday",
          genre: "Political",
        },
        {
          id: "lf-7",
          name: "Panel: Disability Cuts: The Fight Back",
          time: "13:30-14:30",
          day: "Sunday",
          genre: "Political",
        },
        {
          id: "lf-8",
          name: "Panel: How to Fix the Crisis Care",
          time: "12:00-13:00",
          day: "Sunday",
          genre: "Political",
        },
        { id: "lf-9", name: "Kate Nash", time: "21:00-22:00", day: "Saturday", genre: "Indie Pop" },
        { id: "lf-10", name: "Lambrini Girls", time: "19:50-20:30", day: "Saturday", genre: "Punk" },
        { id: "lf-11", name: "The Guest List", time: "18:40-19:20", day: "Saturday", genre: "Hip Hop" },
        { id: "lf-12", name: "Chloe Slater", time: "17:35-18:10", day: "Saturday", genre: "Folk" },
        { id: "lf-13", name: "Girlband!", time: "16:30-17:05", day: "Saturday", genre: "Rock" },
        {
          id: "lf-14",
          name: "Radical Round Up: with Billy Bragg",
          time: "15:00-16:00",
          day: "Saturday",
          genre: "Political",
        },
        {
          id: "lf-15",
          name: "Panel: Saving the Planet but not",
          time: "13:30-14:30",
          day: "Saturday",
          genre: "Political",
        },
        {
          id: "lf-16",
          name: "Panel: Confronting the Rise of the Far",
          time: "12:00-13:00",
          day: "Saturday",
          genre: "Political",
        },
        { id: "lf-17", name: "Billy Bragg", time: "21:00-22:00", day: "Friday", genre: "Folk Punk" },
        { id: "lf-18", name: "Antony Szmierek", time: "19:50-20:30", day: "Friday", genre: "Folk" },
        { id: "lf-19", name: "Jasmine.4.T", time: "18:40-19:20", day: "Friday", genre: "R&B" },
        { id: "lf-20", name: "Gurriers", time: "17:35-18:10", day: "Friday", genre: "Punk" },
        { id: "lf-21", name: "The Meffs", time: "16:30-17:05", day: "Friday", genre: "Punk" },
        {
          id: "lf-22",
          name: "Radical Round Up: with Billy Bragg",
          time: "15:00-16:00",
          day: "Friday",
          genre: "Political",
        },
        {
          id: "lf-23",
          name: "Panel: Feminism in the Age of the",
          time: "13:30-14:30",
          day: "Friday",
          genre: "Political",
        },
        { id: "lf-24", name: "Panel: What Next for the Left", time: "12:00-13:00", day: "Friday", genre: "Political" },
      ],
    },
    // Add more stages as needed...
  ],
}
